apiVersion: v1
kind: Service
metadata:
  name: helloworld
spec:
  type: {{ .Values.service.type }}
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
