name: CD Pipeline

on:
  push:
    branches: [release/uat, main]

jobs:
  deploy-and-validate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download Scan Artifact from release/dev
      uses: actions/download-artifact@v4
      with:
        name: scan-results-${{ github.sha }}
        path: scan-results/

    - name: Run Scan Validation Script
      run: |
        python3 scripts/validate-scan.py
      env:
        IMAGE_NAME: helloworld
        IMAGE_TAG: ${{ github.sha }}

    - name: Set up Kubeconfig for Docker Desktop
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG_CONTENTS }}" > ~/.kube/config

    - name: Pull Docker Image from Docker Hub
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/helloworld:${{ github.sha }}

    - name: Deploy using Helm
      run: |
        helm upgrade --install helloworld charts/helloworld \
          --set image.repository=${{ secrets.DOCKER_USERNAME }}/helloworld \
          --set image.tag=${{ github.sha }}
