on:
  push:
    branches: [release/dev, release/uat, main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/helloworld:${{ github.sha }} ./app

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/helloworld:${{ github.sha }}

    - name: Install Trivy and Scan Image
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        ./bin/trivy image --format json --output scan-result.json ${{ secrets.DOCKER_USERNAME }}/helloworld:${{ github.sha }}

    - name: Conditionally Save and Commit Scan Results
      if: github.ref == 'refs/heads/release/dev'
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
      run: |
        mkdir -p scan-results
        cp scan-result.json scan-results/helloworld-${{ github.sha }}.json
        git config user.name "ci-bot"
        git config user.email "ci@pipeline.local"
        git pull --rebase
        git add scan-results/
        git commit -m "Add scan result for ${{ github.sha }}"
        git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}
        git push origin HEAD:${{ github.ref_name }}     