name: CI Pipeline

on:
  push:
    branches: [release/dev, release/uat, main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/helloworld:${{ github.sha }} ./app

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/helloworld:${{ github.sha }}

    - name: Install Trivy and Scan Image
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        mkdir -p scan-results
        ./bin/trivy image --format json \
        --output scan-results/helloworld-${{ github.sha }}.json \
        ${{ secrets.DOCKER_USERNAME }}/helloworld:${{ github.sha }}

    - name: Upload Scan Results Artifact (Only on release/dev) ✅
      if: github.ref == 'refs/heads/release/dev'
      uses: actions/upload-artifact@v3
      with:
        name: scan-results-${{ github.sha }}
        path: scan-results/
