name: CI Pipeline

on:
  push:
    branches: [release/dev, release/uat, main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Set up GCP Credentials
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Configure gcloud
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

    - name: Build Docker Image
      run: |
        docker build -t helloworld:${{ github.sha }} ./app
        docker tag helloworld:${{ github.sha }} gcr.io/${{ secrets.GCP_PROJECT_ID }}/helloworld:${{ github.sha }}

    - name: Scan Image with Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh
        ./trivy image --format json --output scan-result.json gcr.io/${{ secrets.GCP_PROJECT_ID }}/helloworld:${{ github.sha }}

    - name: Upload Scan Result to GCS
      run: |
        gsutil cp scan-result.json gs://${{ secrets.GCS_BUCKET_NAME }}/scan-results/helloworld-${{ github.sha }}.json

    - name: Push Image to GCR
      run: |
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/helloworld:${{ github.sha }}
