name: Propose Governance Sync to UAT and Main

on:
  push:
    branches:
      - ci-config
    paths:
      - 'governance/**'
      - 'scripts/validate-scan.py'

jobs:
  sync-governance:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Create Pull Request to release/uat
      uses: peter-evans/create-pull-request@v5
      with:
        base: release/uat
        branch: governance-sync/uat
        title: "Governance Sync: Update UAT"
        body: |
          This PR syncs governance and validation logic from `ci-config` into `release/uat`.

          ✅ Files:
          - `governance/`
          - `scripts/validate-scan.py`

        commit-message: "Sync governance to UAT from ci-config"
        delete-branch: true

    - name: Create Pull Request to main
      uses: peter-evans/create-pull-request@v5
      with:
        base: main
        branch: governance-sync/main
        title: "Governance Sync: Update Main"
        body: |
          This PR syncs governance and validation logic from `ci-config` into `main`.

          ✅ Files:
          - `governance/`
          - `scripts/validate-scan.py`

        commit-message: "Sync governance to main from ci-config"
        delete-branch: true
